spring:
  application:
    name: altis-summits
  profiles:
    # If no profile is explicitly passed, default to 'dev' so your local machine always works
    active: dev

server:
  port: 8080

application:
  security:
    jwt:
      # Keep the structure, but default to the env var (useful for both envs)
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}