spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/altis
    username: altis_app
    password: Altisdev@2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Using the standard PostgreSQL dialect since we fixed the Spatial JPQL queries
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE