spring:
  application:
    name: altis-summits

  datasource:
    url: jdbc:postgresql://localhost:5432/altis
    username: altis_app
    password: Altisdev@2026 # e.g., AltisDev2026!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080
